### ISSUE TITLE
Bug: Delete Communities does not display notification

### ISSUE THREAD

**Issue by NgJohn15** [shenoy-anurag/simple-reddit#141]
**Description**
There is no clear notification for the results of deleting a community

**Steps to Reproduce**
1. Go to 'Subreddits'
2. Click on 'Delete Community'
3. Populate any of the fields
4. Click on 'Delete'

**Expected behavior**
A snack bar should display providing the user information whether or not the community was deleted or if something is wrong.

**Comment by manojjampana** [comment]
fix: bug fixed using a snackbar
