### ISSUE TITLE
Bug: Create Community

### ISSUE THREAD

**Issue by NgJohn15** [shenoy-anurag/simple-reddit#142]
**Description**
Creating community doesn't clearly show what is necessary or pull relevant information

**Steps to Reproduce**
1. Go to 'Subreddits'
2. Click on 'Create New Community'
3. Populate fields
4. Click on 'Create Subreddit'

**Expected behavior**
User ID should populate from logged in user, or prompt user to log in if not logged in.

**Comment by manojjampana** [comment]
fixed: Snackbar notifications to inform the user of actions. (Failed, Sucess, etc)
