### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by ganesansanthanam** [shenoy-anurag/simple-reddit#23]
The user should be able to use the feature to reset the password.
And some kind of verification to provide the password strength (Note: Yet to confirm the secondary that is the password strength)

**Comment by ganesansanthanam** [comment]
moved to sprint 2

**Comment by Ganesh96** [comment]
Moved to Sprint 3, as this depends on JWT authorized token. The token authorization is to be done for all APIs posts, communities ,profiles during sprint 3

**Comment by Ganesh96** [comment]
Password recovery is moved to Sprint4, as @Ganesh96 is planning to include using 3 party services for the user story and needs some more time to implement as per want
