### ISSUE TITLE
Bug: user being able to create post without logging in

### ISSUE THREAD

**Issue by Ganesh96** [shenoy-anurag/simple-reddit#236]
**Description**
User is able to create posts without logging in, that should be avoided

**Steps to Reproduce**
1. Go home
2. Click on create a post
43 See the bug

**Expected behavior**
user should login to create post and field for username is not needed

**Screenshots**
![image](https://user-images.githubusercontent.com/10339239/161396815-103c1f65-8ebd-40e1-8dce-0d599c4d1454.png)

**Comment by manojjampana** [comment]
User now gets prompted to Login in order to create a post

**Comment by manojjampana** [comment]
Removed username field during creating a post. Now the username is automatically obtained from logged in user data
