### ISSUE TITLE
Bug: Post Ratings are not capped

### ISSUE THREAD

**Issue by NgJohn15** [shenoy-anurag/simple-reddit#346]
**Description**
A logged-in user can infinitely vote on a post, changing the overall rating.

**Steps to Reproduce**
1. Log In
2. Spam click upvote or downvote.
3. Watch rating skyrocket up and down.

**Expected behavior**
The user should only be able to increment the post up once or down once.

**Comment by shenoy-anurag** [comment]
Nice catch @NgJohn15. I've made a pull request for the same, once we merge it, we can close this issue.
