### ISSUE TITLE
Bug: DEL Comments

### ISSUE THREAD

**Issue by NgJohn15** [shenoy-anurag/simple-reddit#349]
**Description**
DEL Comments currently uses DEL with a body. FE is unable to utilize DEL body payloads. Either switch it to POST or GET with query Params. 

**Expected behavior**
Given a Comment ID and username delete the comment if the username is the correct logged-in user.

**Comment by shenoy-anurag** [comment]
Delete Comments API is already using Query Parameters.
I believe the confusion was caused due to the documentation.
Let me know if there's any other issue, and I'll re-open.

**Comment by shenoy-anurag** [comment]
I'll be changing the HTTP method to POST as DELETE method doesn't have query params.
